### ISSUE TITLE
pygmalion master does not build

### ISSUE THREAD

**Issue by anderspapitto** [sethfowler/pygmalion#143]
The pygmalion.cabal file requires 

network-conduit >= 1.0.1

but then tries (in RPC/Client.hs) to import Data.Conduit.Network.Unix, which is not exposed by version 1.0.1 of network-conduit

**Comment by sethfowler** [comment]
I'm afraid pygmalion is under heavy development right now in branches. I'm working on improving indexing performance; I've reduced it by about 95% over the past couple of months. Unfortunately, that means I'm not spending much time on the master branch, and I haven't been focused on getting pull requests merged for some of my dependencies. It also means that there are some significant regressions I need to clean up, so tread lightly. =)

I hope to get things more stable in the next couple of weeks, but if you still want to get started right away, you can use
the version of the network-conduit package from the `unix-domain-sockets` branch in my fork of conduit. At the time I made that fork, there was no network-conduit 1.0.1, so you wouldn't have been able to build without my fork at all, but I see a new version was released recently.

**Comment by sethfowler** [comment]
I'll keep this open as a reminder to merge my changes to both conduit and LibClang (you'll need the `llvm3.4-fast` branch from my fork) ASAP.

**Comment by sethfowler** [comment]
I've submitted pull requests for `conduit`, `direct-sqlite`, and `LibClang`. Once those are all merged it should be possible to build pygmalion with libraries from Hackage.
